[package]
name = "app"
version = "0.1.0"
description = "Taxorium — Sistema de Facturación"
authors = ["Aaron Lomas"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
rusqlite_migration = "1.2"
boveda-core = { git = "https://github.com/aaronlomas/boveda-core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"

# SQLCipher — base de datos encriptada
rusqlite = { version = "0.32", features = ["bundled-sqlcipher"] }

# Para manejo de errores y utilidades
thiserror = "2.0"
reqwest = { version = "0.13.3", features = ["form", "json"] }
hmac = "0.12.1"
sha2 = "0.10.9"
subtle = "2.5"
machine-uid = "0.6.0"
tera = "1.19"
lazy_static = "1.4"
base64 = "0.22"
chrono = "0.4"
# Servidor HTTP local (Axum)
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
quick-xml = "0.37"
zip = "4.2.0"
