export interface UnitOption {
	value: string; // SUNAT Code (e.g. 'NIU', 'ZZ', 'BX')
	label: string; // Description / Display label
	symbol?: string;
}

export const SUNAT_UNITS: UnitOption[] = [
	{ value: '4A', label: 'BOBINAS (BOB)', symbol: 'BOB' },
	{ value: 'AV', label: 'CÁPSULA (CAPS)', symbol: 'CAPS' },
	{ value: 'BE', label: 'FARDO (FARD)', symbol: 'FARD' },
	{ value: 'BG', label: 'BOLSA (BOLS)', symbol: 'BOLS' },
	{ value: 'BJ', label: 'BALDE (BALD)', symbol: 'BALD' },
	{ value: 'BLL', label: 'BARRILES (BRL)', symbol: 'BRL' },
	{ value: 'BO', label: 'BOTELLAS (BOT)', symbol: 'BOT' },
	{ value: 'BT', label: 'TORNILLO (TORN)', symbol: 'TORN' },
	{ value: 'BX', label: 'CAJA (CAJ)', symbol: 'CAJ' },
	{ value: 'C62', label: 'PIEZAS (PZ)', symbol: 'PZ' },
	{ value: 'CA', label: 'LATAS (LAT)', symbol: 'LAT' },
	{ value: 'CEN', label: 'CIENTO DE UNIDADES (CTO)', symbol: 'CTO' },
	{ value: 'CH', label: 'ENVASE (ENV)', symbol: 'ENV' },
	{ value: 'CJ', label: 'CONOS (CN)', symbol: 'CN' },
	{ value: 'CMK', label: 'CENTÍMETRO CUADRADO (CM2)', symbol: 'CM2' },
	{ value: 'CMQ', label: 'CENTÍMETRO CÚBICO (CM3)', symbol: 'CM3' },
	{ value: 'CMT', label: 'CENTÍMETRO LINEAL (CM)', symbol: 'CM' },
	{ value: 'CT', label: 'CARTONES (CTON)', symbol: 'CTON' },
	{ value: 'CY', label: 'CILINDRO (CIL)', symbol: 'CIL' },
	{ value: 'DR', label: 'TAMBOR (TAMB)', symbol: 'TAMB' },
	{ value: 'DZN', label: 'DOCENA (DOC)', symbol: 'DOC' },
	{ value: 'DZP', label: 'DOCENA POR 10**6 (DOC2)', symbol: 'DOC2' },
	{ value: 'FOT', label: 'PIES (PIE)', symbol: 'PIE' },
	{ value: 'FTK', label: 'PIES CUADRADOS (PIE2)', symbol: 'PIE2' },
	{ value: 'FTQ', label: 'PIES CÚBICOS (PIE3)', symbol: 'PIE3' },
	{ value: 'GLI', label: 'GALÓN INGLÉS (GL)', symbol: 'GL' },
	{ value: 'GLL', label: 'US GALLON (GL)', symbol: 'GL' },
	{ value: 'GRM', label: 'GRAMO (GR)', symbol: 'GR' },
	{ value: 'GRO', label: 'GRUESA (DOC2)', symbol: 'DOC2' },
	{ value: 'HD', label: 'MEDIA DOCENA (1/2 DOC)', symbol: '1/2 DOC' },
	{ value: 'HLT', label: 'HECTOLITRO (HL)', symbol: 'HL' },
	{ value: 'HT', label: 'MEDIA HORA (1/2 H)', symbol: '1/2 H' },
	{ value: 'HUR', label: 'HORA (HR)', symbol: 'HR' },
	{ value: 'INH', label: 'PULGADAS (INCH)', symbol: 'INCH' },
	{ value: 'JG', label: 'JARRA (JARR)', symbol: 'JARR' },
	{ value: 'JR', label: 'FRASCO (FCO)', symbol: 'FCO' },
	{ value: 'KGM', label: 'KILOGRAMO (KG)', symbol: 'KG' },
	{ value: 'KT', label: 'KIT (KIT)', symbol: 'KIT' },
	{ value: 'KTM', label: 'KILÓMETRO (KM)', symbol: 'KM' },
	{ value: 'KWH', label: 'KILOVATIO HORA (KWxH)', symbol: 'KWxH' },
	{ value: 'LBR', label: 'LIBRAS (LB)', symbol: 'LB' },
	{ value: 'LEF', label: 'HOJA (HOJA)', symbol: 'HOJA' },
	{ value: 'LTR', label: 'LITRO (LT)', symbol: 'LT' },
	{ value: 'MGM', label: 'MILIGRAMO (MG)', symbol: 'MG' },
	{ value: 'MLT', label: 'MILILITRO (ML)', symbol: 'ML' },
	{ value: 'MMK', label: 'MILÍMETRO CUADRADO (MM2)', symbol: 'MM2' },
	{ value: 'MMQ', label: 'MILÍMETRO CÚBICO (MM3)', symbol: 'MM3' },
	{ value: 'MMT', label: 'MILÍMETRO (MM)', symbol: 'MM' },
	{ value: 'MTK', label: 'METRO CUADRADO (M2)', symbol: 'M2' },
	{ value: 'MTQ', label: 'METRO CÚBICO (M3)', symbol: 'M3' },
	{ value: 'MTR', label: 'METRO (M)', symbol: 'M' },
	{ value: 'MWH', label: 'MEGAVATIO HORA (MWxH)', symbol: 'MWxH' },
	{ value: 'NIU', label: 'UNIDAD (BIENES) - UND', symbol: 'UND' },
	{ value: 'ONZ', label: 'ONZAS (ONZ)', symbol: 'ONZ' },
	{ value: 'PF', label: 'PALETAS (PAL)', symbol: 'PAL' },
	{ value: 'PG', label: 'PLACAS (PLAC)', symbol: 'PLAC' },
	{ value: 'PK', label: 'PAQUETE (PQT)', symbol: 'PQT' },
	{ value: 'PR', label: 'PAR (PAR)', symbol: 'PAR' },
	{ value: 'QD', label: 'CUARTO DE DOCENA (1/4 DOC)', symbol: '1/4 DOC' },
	{ value: 'RD', label: 'VARILLA (VAR)', symbol: 'VAR' },
	{ value: 'RL', label: 'CARRETE (CRR)', symbol: 'CRR' },
	{ value: 'RM', label: 'RESMA (RESM)', symbol: 'RESM' },
	{ value: 'SA', label: 'SACO (SCO)', symbol: 'SCO' },
	{ value: 'SEC', label: 'SEGUNDO (SEG)', symbol: 'SEG' },
	{ value: 'SET', label: 'JUEGO (JGO)', symbol: 'JGO' },
	{ value: 'ST', label: 'PLIEGO (PLGO)', symbol: 'PLGO' },
	{ value: 'STN', label: 'TONELADA CORTA (TON)', symbol: 'TON' },
	{ value: 'TNE', label: 'TONELADAS (T)', symbol: 'T' },
	{ value: 'TU', label: 'TUBOS (TB)', symbol: 'TB' },
	{ value: 'U2', label: 'TABLETA O BLISTER (BLIS)', symbol: 'BLIS' },
	{ value: 'UM', label: 'MILLÓN DE UNIDADES (MILL)', symbol: 'MILL' },
	{ value: 'YDK', label: 'YARDA CUADRADA (YD2)', symbol: 'YD2' },
	{ value: 'YRD', label: 'YARDA (YD)', symbol: 'YD' },
	{ value: 'ZZ', label: 'UNIDAD (SERVICIOS) - SERV', symbol: 'SERV' }
];
